apiVersion: v1

kind: Service
metadata:
    name  : nginx-service
    annotations:
        metallb.universe.tf/allow-shared-ip: services
    labels:
        app: nginx
        env: ft_services
        owner : ammuriel
spec:
    type    : LoadBalancer
    selector:
        project: nginx
    ports:
        - name      : http
          protocol  : TCP
          port      : 80
# Redirect
          targetPort: 80
        - name      : https
          protocol  : TCP
          port      : 443
          targetPort: 443
        - name      : ssh
          port      : 22
          targetPort: 22

---

apiVersion : apps/v1

kind       : Deployment
metadata   :
    name  : nginx
    labels:
        app   : nginx
        owner : amuriel
spec:
    replicas : 1
    selector :
        matchLabels:
          project: nginx
    template:
        metadata:
          labels:
            project : nginx
            app     : nginx
            owner   : amuriel
        spec:
          containers:
            - name  : nginx
              image : main-nginx:v1
              imagePullPolicy : Never
                  # ports:
                  #     - containerPort: 80
                  #     - containerPort: 443
                  #     - containerPort: 22
