apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.128
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
    owner: amuriel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
        owner: amuriel
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
