apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
    owner: amuriel
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.128
  ports:
    - protocol: TCP
      name: standard
      port: 20
      targetPort: 20
    - protocol: TCP
      name: ftps
      port: 21
      targetPort: 21
    - protocol: TCP
      name: passive-port
      port: 20020
      targetPort: 20020
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
    owner: amuriel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
        owner: amuriel
    spec:
      containers:
        - name: ftps
          image: ftps_image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 20020
